version: "3.7"

volumes:
  customers_postgres_data: {}

services:
  customers:
    build: ./customers/
    container_name: customers
    command: python
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    env_file: customers/.env
    depends_on:
      - postgres_customers
    volumes:
      - ./customers/:${PROJECT_ROOT}
    stdin_open: true
    tty: true
    restart: always
    user: ${SYSTEM_USER_ID}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  postgres_customers:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres_customers
    ports:
    - "5432:5432"
    env_file: customers/.env
    restart: always
    volumes:
      - customers_postgres_data:/var/lib/postgresql/data
